### PR TITLE
Fix to CT, OT, I/SPH Awards page API issues

### PR DESCRIPTION
**Pull request by seakhtar**
Fixes issue(s) #966  .

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/nsf-sbir/ct-fix/awardees/phase-1/)

Changes proposed in this pull request:
-Updates Award APIs to add a "tech topic" field
-Updates Award Phase pages to sort on tech topic field rather than PD
-Updates sorting of awards in Chemical/Enviro Tech, Other Topics, Internet of Things and Semiconductors/Photonic Devices, based on criteria given by PDs

/cc @relevant-people

### CODE REVIEW

**Comment by seakhtar** [comment]
Hi @CecileGonzalez ,

Do you think I should go ahead and merge this, or hold off for Kelly's review? It does make some changes to the API, but from what I can tell, it doesn't affect anything else on the site so it should be safe to make live. 

Just wanted to double-check before I pushed this to the live server.

**Comment by CecileGonzalez** [comment]
What were the changes supposed to accomplish?

Cecile J. Gonzalez
NSF Directorate for Engineering
(703) 292-8538

**Comment by seakhtar** [comment]
The issue is with these two pages:
https://seedfund.nsf.gov/awardees/phase-1/
https://seedfund.nsf.gov/awardees/phase-2/

Currently, the expanding awardee table is created by looking at the Awards API and filtering the awards by PD into each PD's topic area. The problem is that some PDs have multiple topics, and some PDs have been replaced by new PDs but the information hasn't been changed in the API, so the information was displaying incorrectly (or not at all, as in the CT topic's case).
Since this was going to be a problem each time we updated a PD, I suggested giving each awardee a tech topic field so that the expanding table rows could be sorted by topic instead of PD. If you compare the current expanding table with the new page, you can see the awards are sorted differently now (the correct way, according to the PDs that I worked with).

https://seedfund.nsf.gov/awardees/phase-1/      vs.
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/ct-fix/awardees/phase-1/

Hope that makes sense- basically, this should help us keep things clean in the future, but it did require some back-end changes.

**Comment by CecileGonzalez** [comment]
Ok, in that case, there might be more to do, because in the Phase I preview you sent, OT does not appear (while CT does). Is there a display limit of 11 topics, perhaps? And the Phase 2 preview doesn’t show CT.

**Comment by seakhtar** [comment]
I noticed the lack of Other Topics too, but I think that's just how it shakes out with the Phase I awards. I worked with the PD for OT, and he was the one who pointed out that a lot of awards were appearing under OT when they were really a different category, and told me how to re-sort them. I'm guessing that must mean there aren't any Phase 2 CT awards, but I can definitely double check with him!

**Comment by seakhtar** [comment]
Hi @benschrag ,

I'm working with @CecileGonzalez to get this wrapped up and we just wanted to double-check the phase-i and phase-ii awards pages. 

1.Can you confirm that phase-i has no OT topics? 
2. In another thread, I realized you asked for all of phase-ii OT topics to be moved to MI, so can you confirm that is correct as well?

Lastly, phase-ii currently has no CT topics. Is that correct, or are there awards missing from there? 

Here are the updated pages: 
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/ct-fix/awardees/phase-1/
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/ct-fix/awardees/phase-2/

Thanks again for your help!

**Comment by benschrag** [comment]
Hello!

To your questions: yes, Phase I should have no “other topics” proposals.  And yes, you are right about the move of all the former OT to MI.

However, the Phase II page *should* have projects listed under CT.  It looks like most or all of the awards listed in “Biological Technologies” should actually be CT awards.

Would it make sense to send a fully updated list of Phase I and Phase II awards with a column for topic?  If so, please let me know what format would work.

Finally, I gather that we’re not tackling the process of adding the new Phase I (and Phase II) awards made in recent months as part of this update – please confirm!

Cheers,
Ben

**Comment by seakhtar** [comment]
Hi @benschrag ,

A list would be very helpful if you can provide one, thanks! And I think for this particular update, we're focusing on getting the awards filtered into their correct topics. Once that's working correctly, we can probably proceed forward adding the new awards in.

**Comment by benschrag** [comment]
Thanks!  Can you confirm what information you’d need in a spreadsheet of awards?  (FYI if I am pulling this data, it’s just as easy to pull all the new awards as well – but I can segregate them if there’s some reason that we cannot add them at this point.)

Cheers,
Ben

**Comment by seakhtar** [comment]
I think if the rest of the numbers look good, i would just need the names of the CT awards, or anything that looks out of place. Since I manually assign topics to awards, a list of any that need to be upated would be good.
If you can add the new awards in a separate tab or with the distinction they are new, that will probably help to make things quicker once we add them in as well!
Thanks again-

**Comment by seakhtar** [comment]
Hi @CecileGonzalez ,

The new phase II CT awards have been added and the totals now match up with what is on the spreadsheet:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/ct-fix/awardees/phase-2/

With your ok, I can go ahead and merge these CT changes to the live site before getting started on the rest of the topic areas.

**Comment by CecileGonzalez** [comment]
Yes, it looks good.

Cecile J. Gonzalez
NSF Directorate for Engineering
(703) 292-8538

**Pull request merged**
