### PR TITLE
FY2019 Annual events

### PR DESCRIPTION
**Pull request by kmonterr**
Fixes issue(s) # .

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/nsf-sbir/BRANCH_NAME/)

[Preview README for this branch](https://github.com/18F/nsf-sbir/blob/BRANCH_NAME/README.md)

Changes proposed in this pull request:
-
-
-

/cc @relevant-people

### CODE REVIEW

**Comment by kmonterr** [comment]
Hi @seakhtar  - I'd love your help looking at this error! I don't know what is up, but it's not loading.

Thank you so much!
Kelly

**Comment by seakhtar** [comment]
Yes- it still isn't building correctly! Still looking to see what might be causing the issue...

**Comment by kmonterr** [comment]
Thank you! So weird!!

**Comment by seakhtar** [comment]
Hi @kmonterr -

So, I never did figure out the problem... I just re-pasted each line in from a word doc and crossed my fingers :)

I think sometimes the syntax errors are so small they're almost impossible to find. It does seem to have worked though! I thought you might want to check it over one more time to make sure I didn't mess anything up, but otherwise you should be okay to go:
https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/events2019/events/

**Comment by kmonterr** [comment]
thanks, @seakhtar !

**Pull request merged**
