### PR TITLE
Added NuMat Technologies, Inc.

### PR DESCRIPTION
**Pull request by kmonterr**
to the Advanced Manufacturing page. 

@gemfarmer is this the right way to add a company via the API?

Fixes issue(s) #800 

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/nsf-sbir/Adding-NuMat/)

[NuMat details preview](https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/Adding-NuMat/portfolio/details/?company=numat-technologies-inc)

### CODE REVIEW

**Comment by gemfarmer** [comment]
@kmonterr you changed it in the right spot, but the data needs to be rebuilt.

I made a wiki page on how to update API-driven site data [here](https://github.com/18F/nsf-sbir/wiki/Website:-Updating-the-data-from-the-API). The key here is to change the keys to `reset: true` in `_config.yml`.

**Comment by kmonterr** [comment]
awesome! I'd love a training. perhaps the week of 9/11-9/15?? want to set some time up? 

I'm happy to go with your recommendations about reset v true!

**Comment by gemfarmer** [comment]
@kmonterr per my email, it will need to be before the 1st. If that doesn't work, I will be taking leave from 9/1 to 9/8, so I could potentially make a meeting that week as well

**Comment by kmonterr** [comment]
Hi @gemfarmer - It looks great! Oddly, I noticed that we lost Branch Technology LLC with the change. Can we add it back in? Thank you!

**Comment by gemfarmer** [comment]
@kmonterr it looks like branch is [still there](https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/Adding-NuMat/portfolio/details/?company=branch-technology-llc), but isn't shown because of the randomization. Do we want to change the randomization so that some companies _always_ show up, while others make guest appearances now and then??

**Comment by kmonterr** [comment]
I see! I don't think it's necessary. But I think the PDs would like to have 9 companies randomized all time.  Does that work?

**Pull request merged**
