### PR TITLE
Add active styling to navbar links

### PR DESCRIPTION
**Pull request by malinatran**
Fixes issue(s) #679.

/cc @femmebot @OpenGlobe 

I wasn't sure about the styling, but here's a screenshot of what it looks like:
portfolio___nsf_sbir

### CODE REVIEW

**Comment by OpenGlobe** [comment]
Fantastic @malinatran !  Phoebe et al will take a look early next week!

**Comment by kmonterr** [comment]
@femmebot @line47 should I merge this one or delete? Eek!

**Comment by line47** [comment]
I would be in favor of using the method called out in the link mentioned above. 
This PR relies on JS.

**Comment by kmonterr** [comment]
@line47 awesome. I'll delete this pull request then! Thank you!
CC - @seakhtar

**Pull request closed without merging**
