### PR TITLE
adding new awardee kit under Phase I info

### PR DESCRIPTION
**Pull request by kategarklavs**
Just added the link to the new awardee kit (PDF)!

### CODE REVIEW

**Comment by OpenGlobe** [comment]
@kategarklavs where is that file currently?  Is that already in dev somewhere?

**Comment by kategarklavs** [comment]
@OpenGlobe I do not know if it's currently in dev — I copied the address from the issue.

**Comment by OpenGlobe** [comment]
Hey @kategarklavs - can you upload it here?

https://github.com/18F/nsf-sbir/tree/dev/assets/files/grantee-files

and make that a separate PR (or part of this one?)  I'll update the URL in the meantime.

**Comment by kategarklavs** [comment]
@OpenGlobe Done! Just added the file.

**Pull request merged**
