### PR TITLE
Updating url for portfolio search

### PR DESCRIPTION
**Pull request by line47**
Fixes issue(s) https://github.com/18F/nsf-sbir/issues/824

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/nsf-sbir/porfolio-search/)

Changes proposed in this pull request:
- Updating the URL to make the portfolio search use the NSF simple search as opposed to the advanced search

### CODE REVIEW

**Comment by kmonterr** [comment]
oddly, the preview goes to the old explore branch. Will that mess it up if I merge it?

**Comment by line47** [comment]
@kmonterr I'm going to rebuild the branch in Federalist and see if that updates it

**Comment by line47** [comment]
I had the preview URL wrong take a look again @kmonterr

**Comment by line47** [comment]
Yeah that's right - see https://github.com/18F/nsf-sbir/issues/824 for the details

**Comment by kmonterr** [comment]
got it! Thank you, @line47 merging now.

**Pull request merged**
