### PR TITLE
Remove shuffling from awards

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #694 

[CircleCI](https://circleci.com/gh/18F/nsf-sbir/tree/remove-randomness)

[:sunglasses: PREVIEW awardees phase 1](https://federalist.fr.cloud.gov/preview/18f/nsf-sbir/remove-randomness/awardees/phase-1/)
[:sunglasses: PREVIEW awardees phase 1 recent](https://federalist.fr.cloud.gov/preview/18f/nsf-sbir/remove-randomness/awardees/phase-1-recent/)
[:sunglasses: PREVIEW awardees phase 2](https://federalist.fr.cloud.gov/preview/18f/nsf-sbir/remove-randomness/awardees/phase-2/)

[Preview README for this branch](https://github.com/18F/nsf-sbir/blob/remove-randomness/README.md)

Changes proposed in this pull request:
- made it so that all the awardees (phase 1, phase 1 recent, phase 2) pages don't randomize topics or awards

/cc @kmonterr

### CODE REVIEW

**Comment by kmonterr** [comment]
@gemfarmer - @femmebot brings up a good point. It still looks random! is there a way to pull them by alphabetical order? If there isn't, I think by start date would be OK.

**Comment by gemfarmer** [comment]
@femmebot @kmonterr I'll look into it. I thought they were alphabetized, but maybe I overlooked that!

**Comment by gemfarmer** [comment]
Also, by "them", do we mean the companies or the tech topics? Or both?

**Comment by gemfarmer** [comment]
Sorted!

**Comment by gemfarmer** [comment]
@femmebot I guess. Should we keep for now, or should I make more sophisticated `sort` function to override the one Jekyll provides?

**Comment by gemfarmer** [comment]
@femmebot I don't normally take you for the _insensitive sort_, but I'm hurt that you are outsourcing our work ;)

**Comment by kmonterr** [comment]
@gemfarmer thank you! This looks awesome.

**Pull request merged**
