### PR TITLE
use Docker for local development

### PR DESCRIPTION
**Pull request by afeld**
Fixes issue(s) #850.

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/nsf-sbir/dockerize/)

[Preview README for this branch](https://github.com/18F/nsf-sbir/blob/dockerize/README.md)

Changes proposed in this pull request:

Switches the instructions from running Jekyll directly on the development machine, to doing so through Docker. A number of benefits:

* Reduces the number of installation steps
* Works across operating systems, with less command-line experience required
* Reduces the likelihood of "works on my machine" issues

### CODE REVIEW

**Comment by afeld** [comment]
No interest?

**Comment by seakhtar** [comment]
Sorry- I kept thinking this was a project someone was working on! I'll look into it- thank you!

**Comment by seakhtar** [comment]
Okay, I got it installed and running, and used GitHub Desktop to make a local copy of the site. It all seems pretty straightforward, so I'll go ahead and merge (if @kmonterr has no objections).

To make sure I understand, does Docker basically help you set up a local copy of the site, or is it doing other stuff too? Should it always be open when doing development on a local site?

 I also just wanted to get some clarification on when to use a local version of the site vs. when to just make changes online. Should I always be using a local version of the site, or just when doing major development? Are there any other times when local copies should be definitely be used? 

Thanks again!

**Comment by gemfarmer** [comment]
@seakhtar you can think of Docker as a siloed computer that is running on your local computer. It is basically there so that anyone on any computer (Mac, PC, Linux, etc.) can run our code and have the same development experience.

How this works: 
When you run the site locally without Docker, you are using all the configurations within your local environment (operating system, system configurations, other software that you have running). When you run the site locally using Docker, none of the stuff from your computer's local environment impacts the site that you can view locally. 

Local dev vs making changes online:
I would advocate for making as many changes as possible locally, although this definitely is not required. Mostly because it is easier to see errors that might show up on the live site before they go public. That being said, I think making simple text changes on GitHub probably saves time and isn't likely to cause the site to break.

**Comment by kmonterr** [comment]
Thank you both, @seakhtar  and @gemfarmer. I hope you're doing well @gemfarmer ! PLease add it!

**Comment by seakhtar** [comment]
Thank you for the explanation @gemfarmer - that all makes sense! Good to know.

**Pull request merged**
