### PR TITLE
New portfolio link + state-dependent content

### PR DESCRIPTION
**Pull request by kategarklavs**
Added Brian's preferred portfolio link, and re-updated the state-dependent solicitation content.

### CODE REVIEW

**Comment by line47** [comment]
Commit into `kategarklavs-patch-12` from `kategarklavs-patch-5` ?

**Comment by kategarklavs** [comment]
@line47 Yes, I believe so! (And if this turns out to be incorrect, I can go back and make these changes again 👍 )

**Comment by line47** [comment]
hey @kategarklavs here is the conflict, which change is accurate?

```
<<<<<<< kategarklavs-patch-5
For complete program information, check out our latest SBIR solicitation (#) and STTR solicitation (#). 
=======
For complete program information, check out the latest [SBIR solicitation]() or [STTR solicitation]().
>>>>>>> kategarklavs-patch-12
```

**Comment by kategarklavs** [comment]
@line47 Hey! I'd say patch 12 is accurate (though I didn't include solicitation links as there's currently no active solicitation).

**Comment by kategarklavs** [comment]
@line47 Hey! I see now that there are conflicts that need to be resolved — once you're back from DC, would you be able to resolve these?

**Comment by kategarklavs** [comment]
@line47 Thank you!

**Pull request merged**
