### PR TITLE
Adding disclaimer to recent PI stat

### PR DESCRIPTION
**Pull request by kategarklavs**
Adding an explanation of which group this stat actually represents.

Fixes issue(s) # .

[CircleCI](https://circleci.com/gh/18F/nsf-sbir/tree/BRANCH_NAME)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/nsf-sbir/BRANCH_NAME/)

[Preview README for this branch](https://github.com/18F/nsf-sbir/blob/BRANCH_NAME/README.md)

Changes proposed in this pull request:
-
-
-

/cc @relevant-people

### CODE REVIEW

**Comment by kategarklavs** [comment]
@femmebot Howdy! Yes, this is for the first 2017 cohort. I added the disclaimer here to maintain continuity with the other two pages (and to be extra thorough), but if you think it's not necessary, please feel free to delete 👍

**Comment by kategarklavs** [comment]
I didn't find it overly confusing, but I am also not married to it — I can take it out 🎉

**Comment by kategarklavs** [comment]
@femmebot Hey! I removed the citation here — is this good to merge?

**Comment by line47** [comment]
Nothing to merge here after merging other PRs

**Pull request closed without merging**
